### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by woodruffw** [Homebrew/ruby-macho#48]
ruby-macho has matured a lot recently (and is on track to fulfil a lot of its original use cases), so it might be nice to cap off this summer's cumulative work with a symbolic 1.0 release. In my mind, that would mark the transition towards a stable API and a focus on more substantive unit tests.

Here's a shortlist of things that I'd like to include in a 1.0:
- [x] Removal of `set_lc_str_in_cmd` (#45, must-have)
- [x] Uniform LC deduplication (#41, important)
- [x] Proper isolation of constants (#65, important)
- [x] Improved encapsulation of roles (#57, important)
- [ ] Broader LC creation/serialization support (important)
- [x] Performance tweaking/analysis (#63, important)
- [ ] More fully featured command-line utilities (nice-to-have)
- [x] Cleaned up unit tests (#66. nice-to-have)
- [x] Cleaned up library code (lots of ugly bits currently floating around...) (#56, nice-to-have)
  - Remove `@deprecated` methods?

That list is by no means final, of course, and I'm _very_ open to additional (or fewer!) goals for a 1.0. I have some even further goals out there for post-1.0 releases, which I can put in another issue if we think that's worth keeping track of at this point.

cc @UniqMartin

**Comment by UniqMartin** [comment]
Thanks for thinking about the bigger picture! I'll make sure to comment in more detail shortly. Meanwhile, could you go ahead and annotate the items in the check list with importance (I'm thinking something like “must have”, “important, but could live without”, and “nice to have”)? I feel this would be valuable and will help guide you through the remaining GSoC weeks.

Also, I was maybe a bit too bold, but I went ahead and removed the “1.0 release” label (labels should be for long-lasting attributes) and replaced it with a milestone (seemed perfect to better keep track of issues/PRs related to this planned release). As a starting point, I also added the PRs/issues mentioned in your list above to that milestone.

**Comment by woodruffw** [comment]
> Meanwhile, could you go ahead and annotate the items in the check list with importance

Sure thing!


> Also, I was maybe a bit too bold, but I went ahead and removed the “1.0 release” label (labels should be for long-lasting attributes) and replaced it with a milestone


Not a problem, thanks for fixing it :smile:

**Comment by MikeMcQuaid** [comment]
What's the status of this? Just curious!

**Comment by woodruffw** [comment]
@MikeMcQuaid #47 is the only thing blocking this, IMO. Everything else on that checklist is nice-to-have or "important", but wouldn't be a breaking change in the way that constant reorganization will be.

I'm going to try to set some time aside this week for that work, so hopefully we can push a 1.0 release very soon :smile:.

**Comment by MikeMcQuaid** [comment]
@woodruffw Nice!

**Comment by woodruffw** [comment]
This hadn't been updated in a while, but I've gotten the ball rolling again with #65 and #66. With those in, I'm fairly pleased with ruby-macho's state and would be happy making a "stable" release. 

I'll leave this open for a few days before I actually do so, to collect thoughts/ideas.

**Comment by MikeMcQuaid** [comment]
I'd be 👍 on a 1.0 whenever you're happy with it @woodruffw.

**Comment by woodruffw** [comment]
Done! I'll make a revendoring PR soon.
