### ISSUE TITLE
1.1 release

### ISSUE THREAD

**Issue by woodruffw** [Homebrew/ruby-macho#67]
Copied over from 1.0 (didn't make the cut):

- [ ] Broader LC creation/serialization support (important)
- [x] ~~More fully featured command-line utilities (nice-to-have)~~

Some new ideas:

- [ ] I/O and object allocation optimization
- [ ] Expansive `to_hash`/`to_h` support. 
- [x] ~~Refactoring `MachOStructure` to behave more like a DSL (no breaking changes)~~ (see #70)
- [x] Fat file merging (similar to `lipo(1)`) (#68)
- [x] Aggressive delegation and documentation simplification (#69)

**Comment by woodruffw** [comment]
Taking command line utilities off the list, since I'd like to use an external gem like [slop](https://github.com/leejarvis/slop/) and adding dependencies (when only referenced in `bin/`) will affect other projects that use ruby-macho purely as a library.

Instead, I'm going to create `ruby-macho-utils` or something similar as a dumping ground for useful command line utilities.

**Comment by woodruffw** [comment]
Released as of https://github.com/Homebrew/ruby-macho/commit/bc9af1348902a08398c655421447bb5e76dc4c58.
